### ISSUE TITLE
Support Google Analytics

### ISSUE THREAD

**Issue by jacob314** [dart-lang/api.dartlang.org#11]
If you haven't already, please wire in Google Analytics to listen to the events like "display class", etc. You can treat those as Page Views. We can use events for other things like "opened a description for a method". This is really important, we shouldn't launch without analytics wired in. I'm happy to help you with this, too, but it'll take some JS interop (bloats the code size) or some creative uses of postMessage().
-Seth

**Comment by sethladd** [comment]
new dartdoc has analytics for each page
