### ISSUE TITLE
Keyboard shortcuts for search

### ISSUE THREAD

**Issue by jacob314** [dart-lang/api.dartlang.org#13]
Up and down arrow don’t work in search. Hitting enter doesn’t work either. Also I think it’s missing ctrl+3 (cmd+3 on mac) shortcut for focusing on search box.
(feature request) search box + keyboard events: after you search and the completion shows some good results, it would be great if I could navigate to a query result using the keyboard. For example, use the up and down keys to highlight an option, and hit enter to select it.

**Comment by sethladd** [comment]
new dartdoc doesn't have find-as-you-type search. But it does work with the browser's built-in search-in-page features.
