### ISSUE TITLE
Functionality not in the SDK, but provided by pub packages is not discoverable.

### ISSUE THREAD

**Issue by zanderso** [dart-lang/api.dartlang.org#27]
See e.g.: https://code.google.com/p/dart/issues/detail?id=20852

**Comment by sethladd** [comment]
Thanks for the report. We won't solve this with specific functionality in api.dartlang.org. However, we highly recommend that if there's a related and useful package for a library, that the library's docs themselves link to that package.

e.g. the isolates library could link to the isolate package, in its own docs.
