### ISSUE TITLE
Page is empty

### ISSUE THREAD

**Issue by budde377** [dart-lang/api.dartlang.org#36]
When going to the address [http://api.dartlang.org](http://api.dartlang.org) (redirects to [https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/home](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/home)) the page only displays the text: *Dart API Documentation*. 

Similar, when going to [https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:html.Element](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:html.Element) displays: *Dart API Documentation for dart:html.Element*.

This behavior has been observed in Google Chrome (Version 43.0.2357.125 (64-bit)) on Ubuntu 15.04 and  Google Chrome (Version 43.0.2357.124 m) on Windows 8.

**Comment by alan-knight** [comment]
That presumably means it was unable to load the content. That could be a
transient error, or it could be that something in your network
configuration or otherwise is preventing the content from loading. If you
open a JavaScript console, what errors do you see?

**Comment by budde377** [comment]
I see the following error
```
index.html_bootstrap.dart.js:941 Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event provided is null.
```

**Comment by alan-knight** [comment]
I'm guessing there are other errors besides that. That looks like something
that happens after the fact. Are you still having the problem?

**Comment by budde377** [comment]
The problem was solved by disabling the [request maker](https://chrome.google.com/webstore/detail/request-maker/kajfghlhfkcocafkcjlajldicbikpgnp?hl=en) extension in chrome.
