### ISSUE TITLE
/stable directs to a dev channel docs

### ISSUE THREAD

**Issue by sethladd** [dart-lang/api.dartlang.org#39]
If I go to https://new-dartdocs-dot-dartlang-api.appspot.com/stable , I'm redirected to https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.0/index.html

I would expect /stable to go to a stable release.

**Comment by keertip** [comment]
This is intentional for now, as there are no stable docs. Will change once we have a 1.12 stable build.

**Comment by sethladd** [comment]
Thanks for verifying. We'll leave open for tracking.
