### ISSUE TITLE
How do I access older versions of the news with the new server?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/api.dartlang.org#40]
Curious if I can access 1.11 with https://new-dartdocs-dot-dartlang-api.appspot.com ? If so, how?

**Comment by keertip** [comment]
No, don't think so. You need to have the dartdoc-viewer to access the old docs. And since we are doing redirects from current url to new one, this is a difficult proposition. 

We can host the old docs at a different url.

**Comment by sethladd** [comment]
> We can host the old docs at a different url.

Another proposal would be:

 https://new-dartdocs-dot-dartlang-api.appspot.com/1.11.3  will serve the current (dartdocgen + viewer) docs.

I'd like to ensure that, when we turn on the new api.dartlang.org, we don't immediately lose all the old docs. Hosting the last two versions would be helpful. Could we statically upload the dartdocgen+view for the last two versions into cloud storage into the correct bucket? Maybe that's sufficient?

**Comment by sethladd** [comment]
We regenerated the previous two versions of the docs.
