### ISSUE TITLE
Consider using --rel-canonical-prefix for doc builds

### ISSUE THREAD

**Issue by sethladd** [dart-lang/api.dartlang.org#50]
dartdoc now has a --rel-canonical-prefix option. We might consider using this when building the docs for api.dartlang.org

Specifically, we can use --rel-canonical-prefix=https://api.dartlang.org/stable

From https://github.com/dart-lang/dartdoc/issues/912

**Comment by sethladd** [comment]
Thanks!

**Comment by keertip** [comment]
Done. https://codereview.chromium.org/1360823002/

**Comment by sethladd** [comment]
Thanks! /me crosses fingers that it helps

**Comment by keertip** [comment]
:)
