### ISSUE TITLE
Release agnostic links to API pages not working

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/api.dartlang.org#62]
For example, https://api.dartlang.org/stable/dart-io/Directory-class.html should take you to the latest stable page for the Directory class.

But it's not currently working.

We need this for the docs.

thx

**Comment by kwalrath** [comment]
Similarly, URLs like https://api.dartlang.org/dart_io/HttpResponse.html are rewritten to https://api.dartlang.org/stable/1.16.0/index.html, but should instead go to https://api.dartlang.org/stable/1.16.0/dart-io/HttpResponse-class.html (as reported in https://github.com/dart-lang/sdk/issues/26433).

This used to work, and it'd be good to get them working again. The .../stable/... links, however, are more important.

@keertip can you help us figure out how to get the stable links working again?

**Comment by kwalrath** [comment]
I just ran into this problem again with the angular.io/dart docs. It's a real problem to have to point people to a specific version of Dart when you just want the latest stable docs!
