### ISSUE TITLE
api.dartlang.org is not serving version 2.0.0-dev api docs

### ISSUE THREAD

**Issue by whesse** [dart-lang/api.dartlang.org#65]
One problem is that server/scripts/redirector.py needs to check both the major and minor version number in the build_gcs_path function.

Checking everything else, that seems to be the only problem.

**Comment by whesse** [comment]
@keertip @kevmoo 
I can temporarily fix by copying them to the old location.

**Comment by keertip** [comment]
Thanks Bill!

**Comment by whesse** [comment]
The fix should be:
The lines
release_num = nums[1]
if int(release_num) < 15:
shoudl be 
if nums[0] == 1 and nums[1] < 15:

**Comment by jcollins-g** [comment]
This version is now live, should be safe to ship new 2.0 SDKs without breaking api.dartlang.org.

**Comment by dotdoom** [comment]
For whoever is searching for api.dartlang.org for 2.0.0, the link is https://api.dartlang.org/dev/ (redirect), or a specific version is e.g. https://api.dartlang.org/dev/2.0.0-dev.43.0/index.html
